### PR TITLE
(GH-1704) Upgrade 7z to 18.6

### LINKED ISSUE #1704: Update 7z to latest
7zip had a recent release - while there isn't any published CVEs at this time, it's best to go ahead and upgrade.

### PR DESCRIPTION
**Pull request by gep13**
Currently no documented CVE's to point at for this release.

Closes #1704

### CODE REVIEW

**Comment by ferventcoder** [comment]
@gep13 I moved this to stable.

**Comment by ferventcoder** [comment]
I'm not sure if there were any lasting effects on this, but I want to see it before I click the big shiny green button.

**Comment by gep13** [comment]
Sorry, I didn’t add a commit body as I didn’t think there was anything to add. Didn’t think it made sense to put anything in there.

**Comment by ferventcoder** [comment]
No worries, we go there. 👍

**Pull request merged**
