### PR TITLE
(#2345) Avoid any trailing spaces after silentArgs

### PR DESCRIPTION
**Pull request by blami**
## Description Of Changes
Fix a bug where concatenating `$silentArgs` and `$additionalInstallArgs` adds a trailing space at the end of `$silentArgs` even when `$additionalInstallArgs` is empty. Such trailing space can change the meaning of the last positional argument (that may contain spaces).

Final arguments are now created as space joined string arrays filtered down to only non-empty items. Fix is applied to all installer types.

## Motivation and Context
I have some installers doing similar thing as Total Commander (mentioned in #2345 ) - passing installation destination as last positional argument allowing spaces in it. Added trailing space caused by `"$silentArgs $additionalInstallArgs"` when `$additionalInstallArgs` is empty breaks this mechanism and attempts to install to path that ends with space.

NOTE: I am just an ordinary PowerShell user and not really skilled in it so any input on how to get this thing done is welcome. Also wasn't sure if its worth to apply this beyond `EXE` type as `MSI` has its own way of passing arguments. Motivation to fix all types is mostly uniformity.

## Testing
1. Tested installation of several .exe installers (made up mocks and Total Commander) on Windows 11
2. @corbob did some additional testing: https://github.com/chocolatey/choco/pull/3113#issuecomment-2123037178
3. @corbob also added some Pester tests that were tested both in Team City, and by running through the testing vagrant environment.

## Change Types Made
* [x] Bug fix (non-breaking change).
* [ ] Feature / Enhancement (non-breaking change).
* [ ] Breaking change (fix or feature that could cause existing functionality to change).
* [ ] Documentation changes.
* [x] PowerShell code changes.

## Change Checklist
* [ ] Requires a change to the documentation.
* [ ] Documentation has been updated.
* [ ] Tests to cover my changes, have been added.
* [ ] All new and existing tests passed?
* [ ] PowerShell code changes: PowerShell v2 compatibility checked?

## Related Issue
Fixes: #2345

### CODE REVIEW

**Review by corbob — DISMISSED** [review]
Thank you for getting this fixed up @blami. I've taken the liberty of adding a Pester test to this PR, rebased off of develop, then force pushed the change up to your fork. As I've added the Pester tests, I've asked for a review from @gep13 as well.

@gep13: The new Pester tests will fail in Test Kitchen as I have not yet pushed the package to the repositories used by Test Kitchen. Once the PR is merged I'll get those other repositories updated.

**Comment by corbob** [comment]
@blami I've been trying to come up with a manual test to show that this fixes a broken package installation. Unfortunately, I haven't been able to find a version of TotalCommander on the Chocolatey Community Repository that exhibits this behaviour. Do you have a package available that I could use to demonstrate that this fix resolves the issue with that package? The pester tests I added show that the space is gone, but having another verification would be very helpful.

**Comment by blami** [comment]
@corbob Thanks a lot for picking up this! I just looked at Total Commander package in community and it should be still broken. This bug only surfaces if you set install location parameter.

I cannot share our private repo but package excerpt that requires the fix is roughly:
``` powershell
﻿$ErrorActionPreference = 'Stop' # stop on all errors
$toolsDir   = "$(Split-Path -parent $MyInvocation.MyCommand.Definition)"
$url        = 'https://totalcommander.ch/1052/tcmd1052x64.exe'

$packageArgs = @{
  packageName   = $env:ChocolateyPackageName
  unzipLocation = $toolsDir
  fileType      = 'EXE'
  url           = $url
  softwareName  = 'Total Commander*'

  # https://www.ghisler.ch/wiki/index.php?title=Installer#Description_of_switches_and_parameters
  silentArgs    = '/A1H1M0G1D0FN"*" U:\Program Files\TotalCmd'

  validExitCodes= @(0)
}

Install-ChocolateyPackage @packageArgs
```

Hope this helps.

**Review by gep13 — APPROVED** [review]
LGTM!

**Comment by gep13** [comment]
@blami thank you for raising this PR, your first to Chocolatey CLI, and thanks to @corbob thank you for getting this over the finish line!

**Pull request merged**
