### PR TITLE
(GH-480) /All should be the final argument to dism.exe

### PR DESCRIPTION
**Pull request by jbuedel**
Fixes https://github.com/chocolatey/choco/issues/480

### CODE REVIEW

**Comment by jbuedel** [comment]
Obviously I still have some work to do. I'll see what I can do this weekend.

**Comment by ferventcoder** [comment]
So this looks good. You need to update your git commit message as stated in CONTRIBUTING. Read over that on how to push and updated version of your commit as well.

**Comment by jbuedel** [comment]
I made the fix to the commit message. Sorry I missed that.

I swear there was some tests failing when I originally made the pull request. Hence my note about "still have work to do".

**Comment by ferventcoder** [comment]
Thanks!

**Comment by ferventcoder** [comment]
Tests were failing. But they were also failing in stable and master. Once I fixed those I reran the tests in this PR.

**Comment by mwrock** [comment]
Will a new nuget prerelease be dropped with this any time soon?

**Comment by ferventcoder** [comment]
@mwrock that can totally happen :)

**Pull request merged**
