### PR TITLE
(#2443) Fix misspellings for profile text

### PR DESCRIPTION
**Pull request by vexx32**
## Description Of Changes

Fixed a couple minor misspellings in the comments we're adding to folks' profiles in the Chocolatey install.

## Motivation and Context

Noticed it in the testing, figured we may as well fix it.

## Testing

N/A, only code comments edited.

## Change Types Made

* [x] Doc/comments updated
* [ ] Bug fix (non-breaking change)
* [ ] Feature / Enhancement (non-breaking change)
* [ ] Breaking change (fix or feature that could cause existing functionality to change)
* [ ] PowerShell code changes.

## Related Issue

#2443

## Change Checklist

* [ ] Requires a change to the documentation
* [x] Documentation has been updated
* [ ] Tests to cover my changes, have been added
* [x] All new and existing tests passed.
* [ ] PowerShell v2 compatibility checked.

### CODE REVIEW

**Review by AdmiringWorm — COMMENTED** [review]
The changes look good to me, however as this was added in v1.0.0 and targeting #2443, the commit and PR fixing the grammar/spelling mistakes should probably target the same issue.

**Comment by vexx32** [comment]
Good idea, I'll update the commit.

**Review by gep13 — APPROVED** [review]
LGTM!

**Comment by gep13** [comment]
@vexx32 thank you for noticing and for getting this fixed up!

**Pull request merged**
