### PR TITLE
[DO NOT MERGE] Create Get-Proxy

### PR DESCRIPTION
**Pull request by kkdd**

### CODE REVIEW

**Comment by ferventcoder** [comment]
Hi @kkdd - I don't have any context of what this change is supposed to achieve. Perhaps you should read over our CONTRIBUTING document first, then make adjustments to this PR. Thanks!

**Comment by kkdd** [comment]
- created: Get-Proxy.ps1
- modified: Get-WebFile.ps1, Get-WebHeaders.ps1

**Comment by ferventcoder** [comment]
@kkdd ping.

**Comment by ferventcoder** [comment]
Since this has already been implemented in #419 and I haven't heard back from you, I'm going to close this.

**Pull request closed without merging**
