### PR TITLE
(#508) Fixes issue with flaky choco-push tests

### PR DESCRIPTION
**Pull request by JPRuskin**
## Description Of Changes
Corrects use of credentials with find command within the choco-push tests.

## Motivation and Context
The tests were failing in odd ways. On investigation, it seems that it was likely matching credentials on an added source with the right path, and ignoring the (invalid) `--api-key` argument being passed in. Credentials should be used for the list command.

## Change Types Made

* [x] Bug fix (non-breaking change).
* ~[ ] Feature / Enhancement (non-breaking change).~
* ~[ ] Breaking change (fix or feature that could cause existing functionality to change).~
* ~[ ] Documentation changes.~
* [x] PowerShell code changes.
    Note: The changes in PowerShell were only to Pester test files.

## Change Checklist

* ~[ ] Requires a change to the documentation.~
* ~[ ] Documentation has been updated.~
* ~[ ] Tests to cover my changes, have been added.~
* [x] All new and existing tests passed?
    Note: This seems to only pass more tests - but I am unsure all tests are passing within TK currently.
* ~[ ]~ PowerShell code changes: PowerShell v2 compatibility checked?
    Note: The changes in PowerShell were only to Pester 5 test files which aren't expected to run on PSv2.

Related to #508 and #2991

### CODE REVIEW

**Review by corbob — CHANGES_REQUESTED** [review]
Looking at the output in Team City I realized why the Limit-Output was put in line with the `ConvertFrom-ChocolateyOutput`. It would be good to get this changed back.

**Review by corbob — APPROVED** [review]
LGTM!

**Comment by JPRuskin** [comment]
Rebased over the latest changes to develop.

**Review by corbob — APPROVED** [review]

**Comment by corbob** [comment]
Thanks for getting these tests cleaned up @JPRuskin 👍

**Pull request merged**
