### PR TITLE
Readme typos fixed.

### PR DESCRIPTION
**Pull request by x-jokay**
Fixed some typos in the readme.md.

### CODE REVIEW

**Comment by ferventcoder** [comment]
Not exactly typos, just missed periods. @x-jokay would you be able to fix your commit message to say `(doc)` or `(maint)`?  

Please see https://github.com/chocolatey/choco/blob/master/CONTRIBUTING.md#contributing for more details.

**Comment by ferventcoder** [comment]
This is a trivial commit - CLA not required to be signed for this contribution.

**Comment by x-jokay** [comment]
Ok, changed the commit accordingly :)

**Comment by ferventcoder** [comment]
Thanks!

**Pull request merged**
