### PR TITLE
(#798) Add parameter to install and upgrade commands to pin after install

### LINKED ISSUE #798: install - pin package during installation
I just found out about chocolately and I think this is a great project!

Reading the issues here, I thought of a feature request.

I think it would be great if you could "pin" a package directly during (after) the installation.

Instead of 

```
choco install googlechrome
choco pin googlechrome
```

something like this
`choco install googlechrome --pin`

This would especialy come in handy when installing a list of packages via package.conf.

```
    <?xml version="1.0" encoding="utf-8"?>
    <packages>
      <package id="googlechrome" pin="true" />
    </packages>
```

Then again this might be obsolet (in some cases) when https://github.com/chocolatey/choco/issues/242 gets implemented.

### PR DESCRIPTION
**Pull request by TheCakeIsNaOH**
## Description Of Changes

This adds a parameter to pin packages after install or upgrade.
It re-uses the code in save_package_information to create the pin file.

## Motivation and Context

See #798

## Testing

- Installed `wget` with `--pin`, checked that it was pinned with `choco pin list`
- Unpinned and uninstalled
- Install `wget` without `--pin`, checked that it was not pinned with `choco pin list`
- Unpinned and uninstalled
- Upgraded `wget` with `--pin`, checked that it was pinned with `choco pin list`
- Unpinned and uninstalled
- Upgraded `wget` without `--pin`, checked that it was not pinned with `choco pin list`
- Unpinned and uninstalled

Create this `packages.config` file:
```
<?xml version="1.0" encoding="utf-8"?>
<packages>
    <package id="wget" pinPackage="true" />
</packages>
```

Install via that file and then check that wget is pinned with `choco pin list`

## Change Types Made

* [ ] Bug fix (non-breaking change)
* [x] Feature / Enhancement (non-breaking change)
* [ ] Breaking change (fix or feature that could cause existing functionality to change)

## Related Issue

Fixes #798

## Change Checklist

* [x] Requires a change to the documentation
* [x] Documentation has been updated
* [x] Tests to cover my changes, have been added
* [x] All new and existing tests passed.
* N/A PowerShell v2 compatibility checked.

### CODE REVIEW

**Comment by TheCakeIsNaOH** [comment]
I am aware that this is a duplicate PR to #1915, I just think that this is a cleaner implementation to add the pin file directly via `save_package_information` instead of calling `_chocolateyPinCommand.set_pin()`

@bergmeister feel free to use my code to update your PR if you want and I can close this PR. It was easier to throw this PR together rather than trying to describe what I am suggesting in writing.

**Review by gep13 — APPROVED** [review]
LGTM!

**Comment by gep13** [comment]
@TheCakeIsNaOH thanks for pulling all this together! I made a slight change in the PR to mark the new option as being available in 1.2.0 rather than 1.1.0.

I will get this merged in, assuming that the CI builds pass.

**Review by gep13 — APPROVED** [review]
LGTM!

**Comment by gep13** [comment]
The failing Ubuntu build here is a known issue, so going to move forward with getting this merged!

**Pull request merged**
