### PR TITLE
(GH-1416) Incorrect documentation for Install-ChocolateyInstallPackage

### LINKED ISSUE #1416: Incorrect documentation for Install-ChocolateyInstallPackage
Documentation for Install-ChocolateyInstallPackage is incorrect.  It contains the following example:

.EXAMPLE
>
Install-ChocolateyInstallPackage -PackageName 'bob' -FileType 'exe' `
  -SilentArgs '/S' `
  -File "$(Split-Path -Parent $MyInvocation.MyCommand.Definition)\bob.exe" `
  -ValidExitCodes = @(0)

The -ValidExitCodes should not have the "=" in it

### PR DESCRIPTION
**Pull request by danyelcampbell**
The -ValidExitCodes should not have the "=" in it

Fix -ValidExitCodes = @(0) to -ValidExitCodes @(0)

Closes #1416

### CODE REVIEW

**Comment by ferventcoder** [comment]
Hi @danyelcampbell, Looks great! Just one bit of fixing and it will be good to pull in. You can do it or I can handle it, your choice. The git commit message should be `(GH-1416) <summary>`. The contributing doc walks through how to do that. Let me know which way you want to go. Thanks!

**Comment by danyelcampbell** [comment]
Oh, I should be able to do that!

**Comment by danyelcampbell** [comment]
well, I've somehow done two reverts....wanted to do just one and edit the commit. No idea how to fix what I have done now D:

**Comment by ferventcoder** [comment]
Hi @danyelcampbell, 
Did you have questions after reading the [CONTRIBUTING document](https://github.com/chocolatey/choco/blob/master/CONTRIBUTING.md) I pointed you to earlier? It's very clear on how to handle the process of using git, it even includes some help on [responding to feedback](https://github.com/chocolatey/choco/blob/master/CONTRIBUTING.md#respond-to-feedback-on-pull-request) - https://github.com/chocolatey/choco/blob/master/CONTRIBUTING.md#respond-to-feedback-on-pull-request.

**Comment by ferventcoder** [comment]
I'm guessing you may have missed a step as this is in your master branch and not under a feature branch.

Reverts are not the best way to manage fixes. 

From where you are now, here is what I would do:

* `git checkout master`
* `git rebase -i HEAD~3` 

* This is going to bring up a screen (notepad-like) showing the last three commits. Two of those are likely the revert commits and the last one should be the original commit. If this is not what you see, close the screen without making any changes.
* If you see those three commits, delete the two revert commits.
* Change the "pick" on the left side of the remaining commit to "r".
* Save and exit the file
* It should immediately bring up another screen asking you to reword the commit message.
* Then when you save and close that, it will work through the other two commits.
* When it is done, `git push origin master --force` (next time ensure you set up a branch).

Hope that helps. Here is an image that is helpful for the rebase part (which can be intimidating at first):

image

**Comment by ferventcoder** [comment]
updated the text above.

**Comment by ferventcoder** [comment]
Some helpful things with git - `choco install gitextensions -y`. I still use this quite a bit of the time in visualization. Plus it is very helpful (and sometimes quicker) when I'm wanting to stage just parts of a file for commit.

It's also helpful with removing commits from a branch.

**Comment by ferventcoder** [comment]
image

**Comment by danyelcampbell** [comment]
Okay, let me give this another shot!

**Comment by danyelcampbell** [comment]
I think I've finally done it! What a learning process this who thing has been :D

**Comment by ferventcoder** [comment]
Awesome! Git is definitely a learning process!

**Comment by gep13** [comment]
This has been merged into the stable branch here: https://github.com/chocolatey/choco/commit/0906de820d74107e03a292e4d3fce55232bd9ec1

Thank you for your contribution!

**Pull request closed without merging**
