### PR TITLE
(GH-1642) Added silent parameter to `Get-ChocolateyUnzip` to suppress the 7z window

### LINKED ISSUE #1642: Hide the 7z CMD window create by Get-ChocolateyUnzip
Currently the Get-ChocolateyUnzip helper function starts a new 7z process, this creates a new CMD window that very briefly popups that happens even when you are not using chocolatey over the command line. I'd suggest adding a 'silent' parameter to suppress this window.

### PR DESCRIPTION
**Pull request by JurjenBiewenga**
Closes #1642

### CODE REVIEW

**Comment by JurjenBiewenga** [comment]
I've implemented your requested changes, would you like me to also set CreateNoWindow on Get-CheckSumValid and InstallBinFile as these also have a hidden window style?

**Comment by JurjenBiewenga** [comment]
Is this acceptable like it is now?

**Comment by ferventcoder** [comment]
@JurjenBiewenga this looks great! If you want to squash that down and make sure your commit messages are per the CONTRIBUTING doc, that will help speed this process up.

**Comment by ferventcoder** [comment]
We can also squash this down for you and get it in.

**Comment by ferventcoder** [comment]
This has been merged into stable at https://github.com/chocolatey/choco/commit/9d5a6d5c8eebab7cf0e4897e67c04e4010b0b379. Thanks for the contribution!

**Pull request closed without merging**
