### PR TITLE
Spaces in buildpath

### PR DESCRIPTION
**Pull request by zippy1981**
Allows you to check out choco to a subfoldr of a folder with spaces in it and still build

### CODE REVIEW

**Comment by ferventcoder** [comment]
You have two commits here that are not necessary - could be that I need to update stable to master still though?

**Comment by ferventcoder** [comment]
okay down to 1 extra commit

**Comment by zippy1981** [comment]
do you want me to merge to stable?

**Comment by ferventcoder** [comment]
I merged stable to master and pushed upstream. There is still one additional commit there. 

Also, I'm not really sure your commit is following what is written in CONTRIBUTING. Would you mind reviewing https://github.com/chocolatey/choco/blob/master/CONTRIBUTING.md#prepare-commits and fix this up?

**Comment by ferventcoder** [comment]
ping @zippy1981

**Comment by ferventcoder** [comment]
Ping. I haven't heard anything for 24 days. If you would like to keep this going please sign the CLA and fix the commit according to what was suggested with CONTRIBUTING.

**Comment by ferventcoder** [comment]
@zippy1981 I apologize, but unfortunately we must close this due to non-response. Please don't feel that closing this means we don't value your contribution. When you are ready to work on this again, please submit a new pull request. Thanks!

**Pull request closed without merging**
