### PR TITLE
(GH-981) Suggest Get-FileHash when applicable

### LINKED ISSUE #981: Don't suggest installing separate "checksum" tool
When installing a package without a checksum, this message is displayed:

> If you are a maintainer attempting to determine the checksum for packaging purposes, please run
> 'choco install checksum' and run 'checksum -t sha256 -f $file'

Installing a separate tool is unnecessary as you can simply use PowerShell to accomplish the same thing:

```
(Get-FileHash -Path $file -Algorithm SHA256).Hash
```

### PR DESCRIPTION
**Pull request by SeanKilleen**
Resolves #981.

For compatibility reasons, Chocolatey suggests using `choco install checksum` to verify checksums.

But, in Powershell v4 and beyond, users could choose to run `Get-FileHash` as well.

This change adds a message in applicable powershell versions (v4.x and later) to suggest this course of action, per the `up-for-grabs` issue.

## Work Breakdown & Remaining

✅ Add version check using `$PSVersionTable.PSVersion.Major`
✅  Add Debug text
❓  Verify that the text is correct when outputted
✅ Build passes
❓ Tests
✅ Update the commit message to wrap at 72 chars (I think I was over in a few places)

### CODE REVIEW

**Comment by SeanKilleen** [comment]
Hey all,

I believe this change has been successful but I'm a little lacking on the knowledge / context to appropriately test this function (willing to do so if someone can point me in the right direction). In the meantime, I'll read up on the docs.

**Comment by SeanKilleen** [comment]
Updated commit message to wrap at or before 72 characters.

**Comment by ferventcoder** [comment]
Hi @SeanKilleen - thanks, this looks great. However there are two commits here. One is a merge. That means you might have missed https://github.com/chocolatey/choco/blob/master/CONTRIBUTING.md#contributing-process. Can you remove that commit please? Thanks!

**Comment by SeanKilleen** [comment]
@ferventcoder weird, not sure why that was -- definitely wasn't the intention. I must have opened the PR and then done an update to my fork and merged it in. I'll fix it up. 👍

**Comment by ferventcoder** [comment]
Still showing two commits. Not sure why, but I can cherry pick this commit in.

**Comment by ferventcoder** [comment]
Validated that this is CRLF line endings for authenticode signing. 👍

**Comment by ferventcoder** [comment]
Cherry picked into stable at https://github.com/chocolatey/choco/commit/8f4fe74f618df312f7773a218e76822a3337129b. Thanks for the contribution!

**Pull request closed without merging**
