### PR TITLE
(GH-15)(GH-9) AutoInstaller Enhancements

### LINKED ISSUE #9: Auto Uninstaller should run every time
Whether or not the powershell ran. Sometimes the cleanup performed by a chocolateyUninstall may not also include the uninstall of a file and sometimes it may not do it quite right.

### LINKED ISSUE #15: Feature flag autouninstaller
Since it is still experimental, turn it off for now and allow explicit opt-in.

### PR DESCRIPTION
**Pull request by ferventcoder**
Feature flag auto uninstaller.

Still in todo:

- [x] Move AutoInstaller to its own service 
- [x] Write specs surrounding autouninstaller service. 
- [x] Run autouninstaller every time, determining if it should run not based on whether posh ran but if the registry keys are still present.

Closes #9
Closes #15

### CODE REVIEW

**Comment by ferventcoder** [comment]
Fixes #9

**Comment by ferventcoder** [comment]
The specs are not passing yet, the tests have issues running as part of the suite but pass in isolation. :/

**Comment by gep13** [comment]
Based on your description, I immediately thought of this setting in ReSharper:

image

But since you are using TestDriven.net, this won't help you, but perhaps there is a similar setting.

**Comment by gep13** [comment]
I had fun with this recently on a Test Suite that I was writing.  Things worked in isolation, but not when running all of them.  Had to enable this setting to get it to work.

**Comment by ferventcoder** [comment]
Is there something for NUnit?

**Comment by gep13** [comment]
> Is there something for NUnit?

Off the top of my head, I am not sure, I will do some digging.

**Comment by ferventcoder** [comment]
test

**Pull request merged**
