### PR TITLE
(maint) README.md - Update "Community tag" link

### PR DESCRIPTION
**Pull request by tirolo**
Changed the link from "Community tag" to "Up for Grabs"

### CODE REVIEW

**Comment by ferventcoder** [comment]
Two of the tests have issues because `C:\Windows` versus `C:\windows`  - not something you need to fix  though.

**Comment by ferventcoder** [comment]
However, your commit is not quite right. It should either contain a GH number or `(maint)`. Plus a commit message body wouldn't hurt (but is not necessary).

**Comment by tirolo** [comment]
Looks better now? :)

**Comment by gep13** [comment]
@tirolo looks good to me! :+1:

**Comment by ferventcoder** [comment]
Thanks!

**Pull request merged**
