### PR TITLE
(GH-1067) Add elevated cmd example

### LINKED ISSUE #1067: [Enhancement] Update `choco new pkg` template to give example of handling nested quoted paths
### What You Are Seeing?
Wasted hours fighting passing a path with spaces through Start-ChocolateyProcessAsAdmin, finally found a parallel example for PowerShell but it isn't present in the template.

### What is Expected?
Having a good example showing how to handle paths with spaces in the `choco new pkg` template.

### PR DESCRIPTION
**Pull request by dragon788**
Having seen many packages with this written in a fragile manner and having perpetuated/contributed to some of the mess, I figured maybe I should offer a better was as penance. This will provide a better example for future folks interacting with applications that still use batch files to install services or other things.

Closes #1067

### CODE REVIEW

**Comment by ferventcoder** [comment]
Looks good, can you squash?

**Comment by dragon788** [comment]
This has been squashed and bonus content added!

**Comment by ferventcoder** [comment]
Thanks!

**Comment by ferventcoder** [comment]
Merged into stable at https://github.com/chocolatey/choco/commit/366a9fb0ae9ee7108af8f019988c5cdced71c503

**Comment by ferventcoder** [comment]
This will be updated and included with 0.10.4. Thanks for your contribution!

**Pull request closed without merging**
