### PR TITLE
(#2227) Bring Ubuntu to 18.04 in Travis

### PR DESCRIPTION
**Pull request by gliptak**
Fixes https://github.com/chocolatey/choco/issues/2227

### CODE REVIEW

**Comment by gliptak** [comment]
@gep13 please review

**Comment by gep13** [comment]
@TheCakeIsNaOH as someone who is more familiar with building the mono compatible version of Chocolatey, would you mind doing a review of this PR?

Thanks!

**Comment by TheCakeIsNaOH** [comment]
@gep13 @gliptak 

So this fixes the SSL issue by bumping the OS version from 16.04 to 18.04, and pulling the newer root certificates from the OS (ca-certificates), which mono can then use. 

My inclination would be  instead to bump the mono version, which would then bring in the newer root certificates directly in mono. This would help avoid getting stuck on an old mono version and causing issues like #1020 

I tried this with #2234, and travis is working fine with the newer mono version there.

**Comment by gep13** [comment]
@TheCakeIsNaOH this seems like a sensible approach to me.  @gliptak what are your thoughts here?  If you wanted to update this PR to use this suggestion, we can look to get it merged in.

**Comment by gliptak** [comment]
I certainly can add Mono bump to `6.12.0` into this PR. I still would recommend bringing Ubuntu more current (and I will remove the cert apt)

**Review by TheCakeIsNaOH — APPROVED** [review]
Looks fine.

**Comment by gep13** [comment]
@gliptak thank you very much for taking the time to get this fixed up, appreciate it! And thanks to @TheCakeIsNaOH for the assist!

**Pull request merged**
