### PR TITLE
(doc) Fix apt-get command line

### PR DESCRIPTION
**Pull request by fracting**
Anyone who has commit access, please feel free to take the fix. No bother to sign a CLA for such a trivial fix. :)

### CODE REVIEW

**Comment by ferventcoder** [comment]
Yes, this constitutes a trivial patch. However, the commit message doesn't fall in line with our CONTRIBUTING documentation. Would you mind reading over that and fixing it up?

Thanks!

**Comment by fracting** [comment]
Hi ferventcoder, thanks for comment, does it work now?

**Comment by ferventcoder** [comment]
The change is fine, but you need to change it in the actual commit message as well - https://github.com/fracting/choco/commit/b922a3dc2bbd31bf8bfc12ecf6a53dbab040c7e4

**Comment by ferventcoder** [comment]
Note that after you fixup the commit, you can repush to the same branch with `--force` - This is considered generally safe. See https://github.com/chocolatey/choco/blob/master/CONTRIBUTING.md#respond-to-feedback-on-pull-request (first section).

**Comment by fracting** [comment]
Sorry, deleted the branch by mistake, will submit a new pull request.

**Comment by ferventcoder** [comment]
Superseded by #45.

**Pull request closed without merging**
