### PR TITLE
(build) Adding TeamCity Build Status Shield

### PR DESCRIPTION
**Pull request by gep13**

### CODE REVIEW

**Comment by ferventcoder** [comment]
:+1:

**Comment by ferventcoder** [comment]
Does that show the current state of the master branch only?

**Comment by ferventcoder** [comment]
I fixed up the appveyor one to exclude the PRs

**Comment by gep13** [comment]
Are you referring to this line of the appveyor.yml?
nuget:
  disable_publish_on_pr: true
If no, what else are you referring to?  The appveyor build is building Pull Requests at the minute.
Gary
Date: Mon, 19 Jan 2015 16:02:39 -0800

**Comment by gep13** [comment]
In all honesty, I am not sure.
Based on the samples that I saw here:
http://shields.io/
And pulling from the existing shield that was on chocolatey/chocolatey it looks like this is the case, yes.

Date: Mon, 19 Jan 2015 16:01:49 -0800

**Comment by gep13** [comment]
> Does that show the current state of the master branch only?

Given that the build status badge is now green, I think that this is the case, and I guess this makes sense, and it matches what the build status badge from AppVeyor is doing as well.

**Comment by ferventcoder** [comment]
Sweet :)

**Pull request merged**
