### PR TITLE
Removing unused variable.

### PR DESCRIPTION
**Pull request by iluxonchik**
Removing unused local variable "count" in NugetService.cs

### CODE REVIEW

**Comment by ferventcoder** [comment]
Are you familiar with our CONTRIBUTING document? Please read over it and adjust your commit message appropriately. This is probably a maint commit.

**Comment by iluxonchik** [comment]
@ferventcoder whoops, my bad, somehow missed that part (about prefixing with the type of change). Will do.

**Comment by iluxonchik** [comment]
@ferventcoder fixed the commit message. Is "Removing" acceptable or should it be "Remove"?

**Comment by ferventcoder** [comment]
Remove. Good catch.

**Comment by ferventcoder** [comment]
Thanks for the fix!

**Comment by iluxonchik** [comment]
@ferventcoder no problem :)

**Pull request closed without merging**
