### PR TITLE
(GH-14) alternative sources

### LINKED ISSUE #14: Alternative sources
Alternate runners ~= alternate sources

* webpi
* ruby
* python
* cygwin
* windowsfeature

etc

### PR DESCRIPTION
**Pull request by ferventcoder**
- [x] set up structure
 - [x] webpi
 - [x] ruby
 - [x] python
 - [x] cygwin
 - [x] windowsfeature
 - [x] packages.config can work with alternate sources

Closes #14

### CODE REVIEW

**Comment by sitano** [comment]
this is awesome! are you going to merge this into mainstream master branch? if yes, can you expose planned date on a schedule?

**Comment by ferventcoder** [comment]
Milestones tend to serve as tentative dates.

**Comment by ferventcoder** [comment]
Schedules not dates sorry

**Comment by ferventcoder** [comment]
This will be released as part of 0.9.10.

**Pull request merged**
