### PR TITLE
(maint) typo in throw for HTTPS but no package checksum

### PR DESCRIPTION
**Pull request by xioustic**
cheksums => checksums

### CODE REVIEW

**Comment by ferventcoder** [comment]
Thanks! This does need `(maint)` prepending the commit message. You can add that or I can add it for you when I pull this in. 

NOTE: This is a trivial commit and is not subject to the CLA.

**Comment by xioustic** [comment]
Hey fc, sent this from my mobile so I won't be able to modify commit msg until tonight, so feel free to do it yourself if you'd like. Apologies for not following any contribution rules. Thanks for your hard work!

**Comment by xioustic** [comment]
fc: Just prefixed the commit with (maint) as requested, assuming the patch is still applicable to current version. Thanks!

**Comment by ferventcoder** [comment]
Looks good!

**Comment by ferventcoder** [comment]
Merged into stable at https://github.com/chocolatey/choco/commit/21751439375d63669c3023bbcbd4c1954aaabcf2

**Comment by ferventcoder** [comment]
Thanks!

**Pull request closed without merging**
