### PR TITLE
[DO NOT MERGE](maint) Do not assume $env:TEMP is set in powershell helper functions

### PR DESCRIPTION
**Pull request by rhillaardvark**
This is an identical fix to a missing TEMP environment variable in chocolatey/chocolatey.org#139

### CODE REVIEW

**Comment by ferventcoder** [comment]
Why is this necessary?

**Comment by ferventcoder** [comment]
I'm asking mostly because we can assume it is set. We set it https://github.com/chocolatey/choco/blob/master/src/chocolatey/infrastructure.app/services/PowershellService.cs#L199

**Comment by rhillaardvark** [comment]
I am calling into chocolatey.dll from a front end that was not setting the CacheLocation, causing the Start-ChocolateyProcessAsAdmin script to fail. Setting the CacheLocation in the configuration fixes the issue, but the change here would provide a fallback/default value for TEMP if it is not specified in the configuration.

**Comment by ferventcoder** [comment]
> I am calling into chocolatey.dll from a front end that was not setting the CacheLocation, causing the Start-ChocolateyProcessAsAdmin script to fail.

Ah, okay! Can you give me more information on this so I can help set you up for the right calls in? As this is something that should definitely still get called.

**Comment by rhillaardvark** [comment]
Your reference above was enough to point me to the fact that I wasn't setting the configuration up properly via the ConfigurationBuilder (I was constructing my own ChocolateyConfiguration). Looks like I've got the primary functions working properly now (List, Install, Uninstall) via the ChocolateyPackageService.

So yes, this is definitely not needed in a properly set up application. I jumped the gun on the PR

**Comment by ferventcoder** [comment]
Are you coming in from the GetChocolatey API? https://github.com/chocolatey/choco/blob/master/src/chocolatey/GetChocolatey.cs#L168

It should guide you to a fluent setup and call for Run.

**Comment by rhillaardvark** [comment]
I looked at using the GetChocolatey API, but in the case of the list command I want to put the package information into a viewmodel, so it made more sense to me to call into the ChocolateyPackageService directly.

**Comment by ferventcoder** [comment]
> I looked at using the GetChocolatey API, but in the case of the list command I want to put the package information into a viewmodel, so it made more sense to me to call into the ChocolateyPackageService directly.

Any issues you can find there are helpful to move it forward. It's still considered a preview, but really the only approved way folks should interact with Chocolatey since it represents the API. If you move out of using that, wild changes can and will occur and b/c we don't support that, you will be left on your own to figure out what changed and how to fix it. Versus using the approved API, if we break it, we fix it, and expected breakages will follow the semver model.

**Comment by rhillaardvark** [comment]
Understood, thanks for the help!

**Pull request closed without merging**
