### PR TITLE
(#2539) Fix script signing issue

### LINKED ISSUE #2539: Choco installation fails.
### What You Are Seeing?
```
PS C:\Users\name> get-executionpolicy
RemoteSigned

PS C:\Users\name> Set-ExecutionPolicy AllSigned -Scope Process -Force; [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072; iex ((New-Object System.Net.WebClient).DownloadString('https://community.chocolatey.org/install.ps1'))

...
Import-Module : File C:\Users\...\AppData\Local\Temp\2\chocolatey\chocoInstall\tools\chocolateyInstall\helpers\chocolateyInstaller.psm1 cannot be loaded. 
The contents of file C:\Users\...\AppData\Local\Temp\2\chocolatey\chocoInstall\tools\chocolateyInstall\helpers\chocolateyInstaller.psm1 might have been changed 
by an unauthorized user or process, because the hash of the file does not match the hash stored in the digital signature. 
The script cannot run on the specified system. For more information, run Get-Help about_Signing..
```

### What is Expected?
Chocolatey to install normally and report success. 

I've never had trouble installing Chocolatey before over the years but today it's not working for two of us on different machines. I see a new version of Chocolatey was released yesterday, and wonder if this is a new issue?

### How Did You Get This To Happen? (Steps to Reproduce)
Steps above were followed in a Powershell window that was started with 'Run as Administrator'

Tested on a Windows 10 Pro workstation and a Windows Server2012 R2 Standard with same results. Neither had Chocolatey installed before.

### Output Log

<details>

<summary>Full Log Output</summary>

<p>

~~~sh
PS C:\Users\UserFoo> Set-ExecutionPolicy AllSigned -Scope Process -Force; [System.Net.ServicePointManager]::
SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072; iex ((New-Object System.Net.WebClient).
DownloadString('https://community.chocolatey.org/install.ps1'))
Forcing web requests to allow TLS v1.2 (Required for requests to Chocolatey.org)
Getting latest version of the Chocolatey package for download.
Not using proxy.
Getting Chocolatey from https://community.chocolatey.org/api/v2/package/chocolatey/0.12.0.
Downloading https://community.chocolatey.org/api/v2/package/chocolatey/0.12.0 to C:\Users\RESEAR~1\AppData\Local\Temp\2\
chocolatey\chocoInstall\chocolatey.zip
Not using proxy.
Extracting C:\Users\RESEAR~1\AppData\Local\Temp\2\chocolatey\chocoInstall\chocolatey.zip to C:\Users\RESEAR~1\AppData\Lo
cal\Temp\2\chocolatey\chocoInstall
Downloading 7-Zip commandline tool prior to extraction.
Downloading https://community.chocolatey.org/7za.exe to C:\Users\RESEAR~1\AppData\Local\Temp\2\chocolatey\chocoInstall\7
za.exe
Not using proxy.
Installing Chocolatey on the local machine

Do you want to run software from this untrusted publisher?
File C:\Users\UserFoo\AppData\Local\Temp\2\chocolatey\chocoInstall\tools\chocolateyInstall.ps1 is published
 by CN="Chocolatey Software, Inc.", O="Chocolatey Software, Inc.", L=Topeka, S=Kansas, C=US and is not trusted on your
system. Only run scripts from trusted publishers.
[V] Never run  [D] Do not run  [R] Run once  [A] Always run  [?] Help (default is "D"): a

Import-Module : File C:\Users\UserFoo\AppData\Local\Temp\2\chocolatey\chocoInstall\tools\chocolateyInstall\
helpers\chocolateyInstaller.psm1 cannot be loaded. The contents of file C:\Users\UserFoo\AppData\Local\Temp
\2\chocolatey\chocoInstall\tools\chocolateyInstall\helpers\chocolateyInstaller.psm1 might have been changed by an
unauthorized user or process, because the hash of the file does not match the hash stored in the digital signature.
The script cannot run on the specified system. For more information, run Get-Help about_Signing..
At C:\Users\UserFoo\AppData\Local\Temp\2\chocolatey\chocoInstall\tools\chocolateysetup.psm1:61 char:3
+   Import-Module $installModule -Force
+   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : SecurityError: (:) [Import-Module], PSSecurityException
    + FullyQualifiedErrorId : UnauthorizedAccess,Microsoft.PowerShell.Commands.ImportModuleCommand
Install-ChocolateyEnvironmentVariable : The term 'Install-ChocolateyEnvironmentVariable' is not recognized as the name
of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included,
verify that the path is correct and try again.
At C:\Users\UserFoo\AppData\Local\Temp\2\chocolatey\chocoInstall\tools\chocolateysetup.psm1:155 char:3
+   Install-ChocolateyEnvironmentVariable -variableName "$chocInstallVariableName" ...
+   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (Install-ChocolateyEnvironmentVariable:String) [], CommandNotFoundExcept
   ion
    + FullyQualifiedErrorId : CommandNotFoundException

Test-ProcessAdminRights : The term 'Test-ProcessAdminRights' is not recognized as the name of a cmdlet, function,
script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is
correct and try again.
At C:\Users\UserFoo\AppData\Local\Temp\2\chocolatey\chocoInstall\tools\chocolateysetup.psm1:156 char:7
+   if (Test-ProcessAdminRights) {
+       ~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (Test-ProcessAdminRights:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

Creating ChocolateyInstall as an environment variable (targeting 'User')
  Setting ChocolateyInstall to 'C:\ProgramData\chocolatey'
WARNING: It's very likely you will need to close and reopen your shell
  before you can use choco.
Install-ChocolateyEnvironmentVariable : The term 'Install-ChocolateyEnvironmentVariable' is not recognized as the name
of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included,
verify that the path is correct and try again.
At C:\Users\UserFoo\AppData\Local\Temp\2\chocolatey\chocoInstall\tools\chocolateysetup.psm1:167 char:3
+   Install-ChocolateyEnvironmentVariable -variableName "$chocInstallVariableName" ...
+   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (Install-ChocolateyEnvironmentVariable:String) [], CommandNotFoundExcept
   ion
    + FullyQualifiedErrorId : CommandNotFoundException

Test-ProcessAdminRights : The term 'Test-ProcessAdminRights' is not recognized as the name of a cmdlet, function,
script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is
correct and try again.
At C:\Users\UserFoo\AppData\Local\Temp\2\chocolatey\chocoInstall\tools\chocolateysetup.psm1:211 char:9
+   if (!(Test-ProcessAdminRights)) {
+         ~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (Test-ProcessAdminRights:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

Restricting write permissions to Administrators
We are setting up the Chocolatey package repository.
The packages themselves go to 'C:\ProgramData\chocolatey\lib'
  (i.e. C:\ProgramData\chocolatey\lib\yourPackageName).
A shim file for the command line goes to 'C:\ProgramData\chocolatey\bin'
  and points to an executable in 'C:\ProgramData\chocolatey\lib\yourPackageName'.

Creating Chocolatey folders if they do not already exist.

WARNING: You can safely ignore errors related to missing log files when
  upgrading from a version of Chocolatey less than 0.9.9.
  'Batch file could not be found' is also safe to ignore.
  'The system cannot find the file specified' - also safe.
chocolatey.nupkg file not installed in lib.
 Attempting to locate it from bootstrapper.
Test-ProcessAdminRights : The term 'Test-ProcessAdminRights' is not recognized as the name of a cmdlet, function,
script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is
correct and try again.
At C:\Users\UserFoo\AppData\Local\Temp\2\chocolatey\chocoInstall\tools\chocolateysetup.psm1:511 char:7
+   if (Test-ProcessAdminRights) {
+       ~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (Test-ProcessAdminRights:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

Install-ChocolateyPath : The term 'Install-ChocolateyPath' is not recognized as the name of a cmdlet, function, script
file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct
and try again.
At C:\Users\UserFoo\AppData\Local\Temp\2\chocolatey\chocoInstall\tools\chocolateysetup.psm1:518 char:3
+   Install-ChocolateyPath -pathToInstall "$chocolateyExePath" -pathType $environm ...
+   ~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (Install-ChocolateyPath:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

Import-Module : File C:\ProgramData\chocolatey\helpers\chocolateyInstaller.psm1 cannot be loaded. The contents of file
C:\ProgramData\chocolatey\helpers\chocolateyInstaller.psm1 might have been changed by an unauthorized user or process,
because the hash of the file does not match the hash stored in the digital signature. The script cannot run on the
specified system. For more information, run Get-Help about_Signing..
At C:\Users\UserFoo\AppData\Local\Temp\2\chocolatey\chocoInstall\tools\chocolateysetup.psm1:120 char:3
+   Import-Module "$realModule" -Force
+   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : SecurityError: (:) [Import-Module], PSSecurityException
    + FullyQualifiedErrorId : UnauthorizedAccess,Microsoft.PowerShell.Commands.ImportModuleCommand
WARNING: Not setting tab completion: Profile file does not exist at
'C:\Users\UserFoo\Documents\WindowsPowerShell\Microsoft.PowerShell_profile.ps1'.
WARNING: Unable to run Chocolately at this time.  It is likely that .Net Framework installation requires a system reboot

Chocolatey (choco.exe) is now ready.
You can call choco from anywhere, command line or powershell by typing choco.
Run choco /? for a list of functions.
You may need to shut down and restart powershell and/or consoles
 first prior to using choco.
Ensuring Chocolatey commands are on the path
Ensuring chocolatey.nupkg is in the lib folder
PS C:\Users\UserFoo>
~~~

</p>

</details>

### PR DESCRIPTION
**Pull request by corbob**
## Description Of Changes

Fix the issue where our signed scripts won't run on Windows when `AllSigned` Execution Policy is set.

## Motivation and Context

We're signing the scripts, so they should be able to run when the signature is verified.

## Testing

1. Moved `chocolateyInstaller.psm1` to a new directory
2. Created a Self signed Code Signing certificate following Microsoft's guidance: https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_signing?view=powershell-5.1#create-a-self-signed-certificate
2. Signed the `chocolateyInstaller.psm1` file following Microsoft docs.
3. Set execution policy to `AllSigned` and tried to import the psm1 file.
4. Noted the failure of not finding files that I didn't copy or sign

Script used for testing:

```powershell
$moduleFile = "$PSScriptRoot\temp\ChocolateyInstaller.psm1"
Copy-Item "$PSScriptRoot\src\chocolatey.resources\helpers\chocolateyInstaller.psm1" $moduleFile
$certificate = Get-ChildItem Cert:\CurrentUser\My -CodeSigningCert
Set-AuthenticodeSignature -FilePath $moduleFile -Certificate $certificate
Set-ExecutionPolicy -ExecutionPolicy AllSigned -Scope Process
Import-Module $moduleFile -Force
Set-ExecutionPolicy -ExecutionPolicy Bypass -Scope Process
```

## Change Types Made

* [x] Bug fix (non-breaking change)
* [ ] Feature / Enhancement (non-breaking change)
* [ ] Breaking change (fix or feature that could cause existing functionality to change)
* [x] PowerShell code changes. - This is just an encoding change, no actual code has changed.

## Related Issue

Fixes #2539 

## Change Checklist

* [ ] Requires a change to the documentation
* [ ] Documentation has been updated
* [ ] Tests to cover my changes, have been added
* [x] All new and existing tests passed.
* [x] PowerShell v2 compatibility checked.

### CODE REVIEW

**Review by vexx32 — APPROVED** [review]
It's unfortunate that something so minute and largely invisible like the BOM can upset the signature verification, it seems like it was only fixed in pwsh itself pretty recently too, so we won't get that fix for a ways yet.

C'est la vie, thanks for tracking this one down! 💖

This looks good to me. Not sure where best to put this in terms of ongoing testing, maybe a Github Action would be appropriate here just for the basic verification that all scripts PR'd into the repo satisfy the requirement or something? 🤔

**Comment by ferventcoder** [comment]
Note another invisible thing is line endings - they can not be mixed, and they can not be LF. They must be CRLF.

**Comment by ferventcoder** [comment]
Note another invisible thing is line endings - they can not be mixed, and they can not be LF. They must be CRLF. It would be good to set up some tests on these things that can be applied to PRs and of course the code at normal intervals to check for that. It was on my list from a long time ago. I put in a bug to PowerShell about the LF line endings and authenticode. 

I had it on my list to eventually have testing surrounding these things for PRs as it is so easy to miss.

**Comment by ferventcoder** [comment]
@corbob you might add the additional test to ensure all line endings are CRLF (with proper approvals from your manager of course). Otherwise we might be right back here if we miss a line ending as it won't pass authenticode signing either.

**Comment by corbob** [comment]
Thanks for the heads up @ferventcoder I've added a test to ensure line endings are CRLF and updated the tests to exclude the files that @gep13 and I had discussed.

**Comment by gep13** [comment]
The failing AppVeyor Build here seems to have been an issue with AppVeyor itself, and not with this change.

**Review by gep13 — APPROVED** [review]
LGTM!

**Comment by gep13** [comment]
image

**Comment by gep13** [comment]
@corbob thank you for finding and fixing this issue!

**Pull request merged**
