### PR TITLE
Remove confusing message since the one right before it says that it won't install

### PR DESCRIPTION
**Pull request by bean5**
I saved with Atom, which automatically cleaned up whitespace stuff as well. The main change was known as lines 437-438.

### CODE REVIEW

**Comment by bean5** [comment]
Hmm. Automatic checks are failing. I'm not sure if those are pre-existing. If this is just deprecated code I modified, I suppose if no one wants to update tests accordingly, we might rather deny this request. 

I'll admit I'm new to Github checks, so I didn't even know to run them before making the request.

**Comment by ferventcoder** [comment]
No worries - have you reviewed the contributing doc?

On Friday, May 1, 2015, Bean <notifications@github.com> wrote:

> Hmm. Automatic checks are failing. I'm not sure if those are pre-existing.
> If this is just deprecated code I modified, I suppose if no one wants to
> update tests accordingly, we might rather deny this request.
>
> I'll admit I'm new to Github checks, so I didn't even know to run them
> before making the request.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/chocolatey/choco/pull/266#issuecomment-98259218>.
>


-- 

Rob
"Be passionate in all you do"

http://devlicio.us/blogs/rob_reynolds
http://ferventcoder.com
http://twitter.com/ferventcoder

**Comment by ferventcoder** [comment]
@bean5 Have you had the opportunity to read and respond to my feedback yet?

**Comment by bean5** [comment]
I read the contrib document, and accepted the CLA. I amended the commit to contain the pull request number. I still don't know how to run the checks locally to determine whether they were already failing. According to your contrib rules, ideally you don't introduce failures. Sorry I don't know how to check locally.

**Comment by ferventcoder** [comment]
@bean5 Thanks for following up. The weird part here is that our contrib documentation may need to state that the issue you link to should be an issue and not a pull request. It also seems that you need to fetch from latest and rebase your changes against that so that the build can be completed. 

If you want to handle those two things, that would be great! If not I can probably move forward with the removal of the message as a doc commit. Let me know.

**Comment by ferventcoder** [comment]
The entire section has been removed so this PR is no longer valid. Thanks for the request though!

**Comment by ferventcoder** [comment]
This was invalidated by #300

**Comment by bean5** [comment]
Glad you found that. The rebase/merge on this would have been more of a beast than it was worth it.

**Pull request closed without merging**
