### PR TITLE
(GH-1364) - update template service to generate UTF8 files without BOM.

### PR DESCRIPTION
**Pull request by Benny1007**
Updated TemplateService.cs to use UTF8Encoding with no BOM when creating the template files in relation to chocolatey#1364

Not sure why other files were updated, this is my first ever pull request.

### CODE REVIEW

**Comment by TheCakeIsNaOH** [comment]
@Benny1007 Are you still interested in completing this?

**Comment by Benny1007** [comment]
i can't even remember this, is it still required?

**Comment by AdmiringWorm** [comment]
@Benny1007 IMO, it is still a valid contribution as files are even being generated with BOM.
It looks like the PR would need to be cleaned up, though, and at least the PowerShell files you have changed to not generate with BOM needs to have BOM (otherwise PowerShell will read them as ASCII).

However, PR #2064 perhaps could supersede this one as it is also up to date.

**Comment by ferventcoder** [comment]
I think we could go for #2064 to supersede this - there were some files in here that did not appear to need to be adjusted that needed to be pulled out. It also doesn't appear that the CLA was signed (CLAHub the older one is showing as not signed, but it could have been at the time this was submitted). Thoughts?

**Comment by TheCakeIsNaOH** [comment]
@gep13 This should be able to be closed as #2064 has been merged

**Comment by gep13** [comment]
@TheCakeIsNaOH makes sense to me.  Thanks for pointing this out!

**Pull request closed without merging**
