### PR TITLE
(#63) Support passing sources by name to push command.

### PR DESCRIPTION
**Pull request by DamianMaslanka5**
Related to #63

### CODE REVIEW

**Comment by DamianMaslanka5** [comment]
@gep13 Updated.

**Comment by DamianMaslanka5** [comment]
@gep13 Can you take a look a this PR again?
Are you going to merge the changes or should I close the PR?

**Comment by gep13** [comment]
@DamianMaslanka5 sorry for not getting back to you sooner about this!  I have started working on going through the backlog of PR's into this repository.  Are you in a position to sign the CLA for the project?  You can find a link in the comment above.  That will allow us to move forward with this change.

**Comment by DamianMaslanka5** [comment]
@gep13 I signed the CLA

**Comment by gep13** [comment]
@DamianMaslanka5 I am coming back to look at this again, and the more I think about this, the more that I think that the current approach used in this PR is not the right one.  Let me try to explain...

Out of the box, Chocolatey ships with the following sources configured:

```
  <sources>
    <source id="chocolatey" value="https://community.chocolatey.org/api/v2/" disabled="false" bypassProxy="false" selfService="false" adminOnly="false" priority="0" />
  </sources>
```

So being able to do something like:

```
choco install windirstat --source="'chocolatey'"
choco install windirstat --source="'https://community.chocolatey.org/api/v2/'"
```

makes a lot of sense, since both of these pieces of information exist in the source element of the chocolatey.config file.

However, when it comes to pushing packages, the sources element in the chocolatey.config file isn't actually used, it is only the entries in the apikey section that are inspected.  By default, there aren't any entries in there, but when populated, it would look something like the following:

```
<apiKeys source="https://push.chocolatey.org/" key="encrypted_stuff" />
```

Now, while there is a source attribute here, there isn't an id attribute as there was before.

In order for this PR to work, there would need to be an additional entry in the source element, so that the API Key could be found, i.e.

```
  <sources>
    <source id="chocolatey" value="https://community.chocolatey.org/api/v2/" disabled="false" bypassProxy="false" selfService="false" adminOnly="false" priority="0" />
    <source id="chocolatey_push" value="https://push.chocolatey.org/" disabled="false" bypassProxy="false" selfService="false" adminOnly="false" priority="0" />
  </sources>
```

But this would lead to duplicated sources being shown when they aren't actually required.

I think the correct approach here would be to add a new attribute onto the apikey elements.

What do you think?

@TheCakeIsNaOH what are your thoughts here, as this likely impacts on your follow up PR for defining a default named push source for Chocolatey commands.

If I am missing something here, then please feel free to let me know.

**Comment by gep13** [comment]
Or, thinking about this some more, after a chat with @pauby...

Do we want/need an additional attribute on the source element, which is the push URL for the source, i.e. the source element for Chocolatey would become:

```
<sources>
    <source id="chocolatey" value="https://community.chocolatey.org/api/v2/" disabled="false" bypassProxy="false" selfService="false" adminOnly="false" priority="0" pushUrl="https://push.chocolatey.org/" />
  </sources>
```

And then this is used to locate the API Key associated with the source when someone does:

```
choco push temp.nupkg --source="'chocolatey'"
```

In the absence of anything defined in the pushUrl, it could fallback to attempting to use the URL in the `value` attribute, which may or may not work.

Thoughts?

**Comment by TheCakeIsNaOH** [comment]
> @TheCakeIsNaOH what are your thoughts here, as this likely impacts on your follow up PR for defining a default named push source for Chocolatey commands.

This only should affect #2430 insofar as it requires I change tests.

The configuration value would still go through the same parsing and whatnot that a source passed in via `--source` would, AFAIK, so it should not matter how it is implemented.

> Do we want/need an additional attribute on the source element, which is the push URL for the source, i.e. the source element for Chocolatey would become:

I'm not really a fan of that. If we are adding elements, IMHO it should go to the apikeys.

> I think the correct approach here would be to add a new attribute onto the apikey elements.

Yes, something like:
`<apiKeys id="chocolatey" source="https://push.chocolatey.org/" key="encrypted_stuff" />`

**Comment by TheCakeIsNaOH** [comment]
Oh, and I could remove the dependency on this from #2430 if desired, then this PR could be updated to add those tests to ensure that a name works with `DefaultPushSource`. That would allow #2430 to be merged.

**Comment by vexx32** [comment]
Apologies @DamianMaslanka5 I hadn't realised #2430 was built off this PR already.

That PR is now merged, so relevant to the discussion above @gep13 I think that's a worthwhile enhancement, but it doesn't necessarily require this PR (or @TheCakeIsNaOH's) to include it IMO. I think that's worth its own separate follow up enhancement issue. I will open a follow up issue to address that.

With that, because the bulk of this PR has been incorporated by merging #2430, I'm going to go ahead and close this one off for now. Thank you for your work here @DamianMaslanka5! 💖

**Pull request closed without merging**
