### PR TITLE
(GH-71) Add priority property to ChocolateySource

### PR DESCRIPTION
**Pull request by RichiCoder1**

### CODE REVIEW

**Comment by ferventcoder** [comment]
Targeting stable will get it out in 0.9.9.9. Targeting master is 0.9.10 era.

**Comment by RichiCoder1** [comment]
I can migrate it over if yah'd like.

**Comment by ferventcoder** [comment]
I can as well :)

**Comment by ferventcoder** [comment]
Just can't quickly click the shiny green button here

**Comment by RichiCoder1** [comment]
Haha, indeed. I definitely wouldn't be against getting this out sooner :)

**Comment by ferventcoder** [comment]
Whoops, the code you need is only available in 0.9.10 haha
so that makes it simple.

**Comment by ferventcoder** [comment]
And completely explains why I didn't get it in

**Comment by RichiCoder1** [comment]
Ahh. Fair enough.

**Pull request merged**
