### PR TITLE
{WIP}(GH-458) .NET 4.5 / TLS v1.2 Support

### LINKED ISSUE #458: Choco / NuGet doesn't support TLS v1.2
https://groups.google.com/d/msgid/chocolatey/a84e2f24-8568-4ec0-927a-d55152b5dbc9%40googlegroups.com?utm_medium=email&utm_source=footer

The tl;dr is http://stackoverflow.com/questions/4137106/are-there-net-implementation-of-tls-1-2

Related to #8 for full implementation

Sorry Windows 2003 fans. We'll also be looking at how we can ensure that it works .

### PR DESCRIPTION
**Pull request by ferventcoder**
So sorry Windows 2003. No Choco 0.9.11 for you.

Closes #458

### CODE REVIEW

**Comment by ferventcoder** [comment]
image

**Comment by RichiCoder1** [comment]
I'm late to respond, but I'mall for jumping to 4.5 as a minimum. I think we moved to 4.5 with GUI already.

**Comment by ferventcoder** [comment]
Looks like travis ci will need fixes.

**Comment by ferventcoder** [comment]
Note that when you switch back and forth from this PR, you must empty out build_output/code_drop or it will throw errors about a missing dependency at you during the build and ILMerge will fail.

**Comment by ferventcoder** [comment]
Also note that Mono doesn't yet support 4.5.2 at the time of this comment.

**Comment by ferventcoder** [comment]
I think we'll close this for now as the big reason for jumping was TLS v1.2 support - we have that in Chocolatey now. See https://github.com/chocolatey/choco/issues/458 for the commits that went in to support this.

**Comment by stephengtuggy** [comment]
Here's another reason for jumping to 4.5.2: 4.0, 4.5, and 4.5.1 are no longer supported (or patched) by Microsoft. https://support.microsoft.com/en-us/lifecycle/search?alpha=.net%20framework

This seems like a pretty big deal to me.

**Comment by ferventcoder** [comment]
@stephengtuggy 4.0 is the minimum supported version. You can be on a newer .Net 4.x with choco.exe and it supports TLS if you have at least 4.5 installed. Does this make sense/adjust your understanding a bit?

**Comment by ferventcoder** [comment]
TLS v1.2 I mean

**Pull request closed without merging**
