### PR TITLE
(#2930) Update GenerateDocs.ps1 for choco-theme

### LINKED ISSUE #2930: Update GenerateDocs.ps1 file to adhere to style guidelines in choco-theme 0.2.0
### Checklist

- [X] I have verified this is the correct repository for opening this issue.
- [X] I have verified no other issues exist related to my request.

### Is Your Feature Request Related To A Problem? Please describe.

Choco-theme has been updated to 0.2.0, and as a part of that, styles for callouts have been changed. Emojis are no  longer used, and the general syntax of them has changed. The GenerateDocs.ps1 file still has the outdated format in it, which will revert back to the old style whenever it is ran. This will cause in consistent styles on docs.chocolatey.org.

### Describe The Solution. Why is it needed?

The GenerateDocs.ps1 file needs updated to use the new alert/callout style that is defined in choco-theme 0.2.0. This involves:

* Switching `:memo:` to use `:choco-info`
* Ensuring the `> :choco-info:` is on one line, followed by an empty `>` and then the body of the text on the third line, also starting with a `>`. 
  * This is the standard syntax in all of Chocolatey's websites
  
The new syntax should look like below:

```
> :choco-info: **NOTE**
>
> Chocolaty is awesome!
```

### Additional Context

This will be documented at a later time at: design.chocolatey.org/components/callouts

### Related Issues

- https://github.com/chocolatey/choco-theme/issues/224

This PR has all related PR's associated with choco-them 0.2.0:
- https://github.com/chocolatey/choco-theme/pull/284

### PR DESCRIPTION
**Pull request by st3phhays**
## Description Of Changes
This file has been updated to adhere to updated style guidlines that have been introduced in choco-theme 0.2.0. Emojis are no longer used, and the general syntax of them has changed.

A few updates were also made to not catch `NOTE:` if it was in the middle of a paragraph, as this would break the layout when generated.

The rules of using callouts will be available at a later date at:

design.chocolatey.org/components/callouts

The choco-theme 0.2.0 PR can be found at:

https://github.com/chocolatey/choco-theme/pull/284

## Motivation and Context
Within the next week, choco-theme 0.2.0 will be rolling out to all the sites. If this PR is not merged and implemented after choco-theme 0.2.0 has been deployed, then the callouts on docs.chocolatey.org will all break when new docs are generated by the GenerateDocs.ps1 script.

## Testing
1. Run GenerateDocs.ps1 from the root of this repository
2. Changed the `.gitignore` file temporally to not ignore `docs/generated`
3. Inspected the generated docs to ensure:
    1. All instances of `:memo:` were converted to :choco-info:
    2. The format of the callouts were as specified:
    ```
    > :choco-info: **NOTE**
    >
    > Chocolatey is awesome!
    ```
    3. If `NOTE:` appeared in the middle of a paragraph, it was not converted to use this layout. Doing so would break the layout of the generated docs.
4. Copied the generated docs into a local version of docs.chocolatey.org and ran the site.
5. Viewed each page of the docs that are generated using this tool to ensure all callouts showed as they should.

### Operating Systems Testing
- Windows 10 Pro

## Change Types Made

* [ ] Bug fix (non-breaking change).
* [x] Feature / Enhancement (non-breaking change).
* [ ] Breaking change (fix or feature that could cause existing functionality to change).
* [ ] Documentation changes.
* [ ] PowerShell code changes.

## Change Checklist

* [ ] Requires a change to the documentation.
* [ ] Documentation has been updated.
* [ ] Tests to cover my changes, have been added.
* [ ] All new and existing tests passed?
* [ ] PowerShell code changes: PowerShell v2 compatibility checked?

## Related Issue
* #2930
* Please see the choco-theme 0.2.0 PR for all related PRs: https://github.com/chocolatey/choco-theme/pull/284

Fixes #2930

### CODE REVIEW

**Comment by st3phhays** [comment]
@gep13  This is ready for review, but is in Draft to ensure it is not merged. Merging of this PR will be done when [all other PRs in choco-theme 0.2.0](https://github.com/chocolatey/choco-theme/pull/284) are reviewed and approved.

**Review by gep13 — DISMISSED** [review]
LGTM!

**Comment by gep13** [comment]
@st3phhays this looks great to me.  I will get this rebased and merged in at some point soon, since we won't be generating docs until the next release of chocolatey/choco.

**Review by gep13 — APPROVED** [review]
LGTM!

**Comment by gep13** [comment]
@st3phhays thanks for getting this fixed up!

**Pull request merged**
