### PR TITLE
Gh686

### PR DESCRIPTION
**Pull request by eeevans**
(GH-686) - Add --includepre option to Upgrade command to allow a package which already has a prerelease version installed to be upgraded to the latest prerelease version.

### CODE REVIEW

**Comment by eeevans** [comment]
My attempt at squashing didn't work

**Comment by ferventcoder** [comment]
ouch on squashing.

**Comment by ferventcoder** [comment]
The right thing seems to be to upgrade UNLESS opted out. Whether it is a prerelease or not is not important to an end user. Thoughts?

so `choco upgrade all --exclude-installed-prereleases`

**Comment by eeevans** [comment]
Yes, that seems a reasonable expectation.  I was just wary of changing current functionality without an explicit warning but I can see how it is a more desired functionality.

**Comment by ferventcoder** [comment]
@eeevans any updates on flipping this?

**Comment by ferventcoder** [comment]
@eeevans Thanks for your contributions, unfortunately we went to the more desired functionality of upgrading packages that are prereleases as well as folks have installed the prerelease, so they want it to upgrade to the latest version (stable or prerelease). The old behavior can be brought back with `--exclude-prerelease` in 0.10.4+.

**Pull request closed without merging**
