### PR TITLE
(#2298) Update post push to CCR message

### LINKED ISSUE #2298: Post "choco push" response message
Following a ```choco push  <package-name>.nupkg```
the following message is reported in magenta text:

```
Your package may be subject to moderation. A moderator will review the
package prior to acceptance. You should have received an email. If you
don't hear back from moderators within 1-3 business days, please reply
to the email and ask for status or use contact site admins on the
package page to contact moderators.

Please ensure your registered email address is correct and emails from
noreply at chocolatey dot org are not being sent to your spam/junk
folder.
```

This message has several problems:

* The message gives unrealistic expectations, moderation queue and process in full can be several weeks depending on the package and the size of the moderation queue to be approved
* The message is slightly ambiguous - 1-3 days should the user expect an e-mail saying it is approved or it is submitted for automated package testing? 
* It encourages replies and contact to site admins for unnecessary workload
* Expect an e-mail, no indication of what "from" it will use, but you may need to reply to it. The only e-mail mentioned specifically is noreply which clearly isn't to be replied to. This is untidy. 

Suggestions:
1. A realistic indication of the length of the entire (typical) approval process in time for submitted packages to appear in the community repository.
2. A link to the dynamic moderation queue highlight the placement of the submitted application in this queue.
3. A more verbose reminder of the approval steps and that it may be an iterative processes in some cases.
4. Any e-mail expected, the address should be listed here so that users can whitelist it lest it be marked as spam by their mail client. Is specifying and e-mail in words to prevent spam OCR still a useful thing these days? If not that should be done away with.
5. A url to help documentation for any more detailed FAQ beyond the scope of this short text.
6. The text reported to users could be dynamically obtained from the internet, that way it could be easily updated if required without the user needing to upgrade choco itself.

It may also be worth considering that by default  "choco push" could display an "Are you sure" notice with some basic pre-push checklist steps which can be over-ridden by a ```-y``` switch for more seasoned package maintainers.

### PR DESCRIPTION
**Pull request by TheCakeIsNaOH**
## Description Of Changes

Updates message with details of the current CCR moderation process.
Adds a link to the moderation documentation.

## Motivation and Context

The current message was written for an older CCR moderation process, and it not accurate anymore.

## Testing

N/A

## Change Types Made

* [ ] Bug fix (non-breaking change)
* [x] Feature / Enhancement (non-breaking change)
* [ ] Breaking change (fix or feature that could cause existing functionality to change)

## Related Issue

Fixes #2298

## Change Checklist

* N/A Requires a change to the documentation
* [x] Documentation has been updated
* N/A Tests to cover my changes, have been added
* [x] All new and existing tests passed.

### CODE REVIEW

**Review by gep13 — APPROVED** [review]
LGTM!

**Comment by gep13** [comment]
@TheCakeIsNaOH I made a couple of minor tweaks to this, but on the whole, this looks good!

I will get this merged in once the CI builds finish.

**Comment by TheCakeIsNaOH** [comment]
@gep13 I like the new short link to the moderation queue. I'll have to update my snippets.

**Comment by gep13** [comment]
The full link is too long compared to the other text, so I thought it made sense to shorten this one.

**Pull request merged**
