### PR TITLE
(#2358) Add official and debug Mono build scripts

### PR DESCRIPTION
**Pull request by TheCakeIsNaOH**
Fixes: #2358

I think we may have to dig into uppercut as well to get the code signing working on Mono.

### CODE REVIEW

**Comment by gep13** [comment]
@TheCakeIsNaOH I have just taken these for a spin on my Mac and they work, although I had to `chmod` them before they would execute.  Is that expected?

**Comment by TheCakeIsNaOH** [comment]
@gep13 No, that is not expected, I think? I'll look into it.

------
> I think we may have to dig into uppercut as well to get the code signing working on Mono.

Ok, yup, this is still building with the unofficial strongname key, and is not trying to codesign. I think the script is fine? But uppercut will have to be fixed to set the official configuration using the official strongnaming key. And I don't quite know enough about authenticode to even know where to start on getting that signing working on linux.

**Comment by TheCakeIsNaOH** [comment]
I think I've fixed it.

**Comment by gep13** [comment]
> But uppercut will have to be fixed to set the official configuration using the official strongnaming key.

Some of this is driven by the presence of certain files on the file system, and environment variables.  Leave this part with me, and I will let you know how I get on.

**Comment by gep13** [comment]
> I think I've fixed it.

Just tested again, and this is now working.

**Review by gep13 — APPROVED** [review]
LGTM!

**Comment by gep13** [comment]
@TheCakeIsNaOH thanks for getting these added!

**Pull request merged**
