### PR TITLE
(#2650) Upgrade 7z to 21.07

### LINKED ISSUE #2650: Bump version of 7za.exe shipped with Chocolatey
The 7za.exe binary and supporting dlls/files we ship with Chocolatey is currently version 18.6.0.0. Can we look to bump this to a later stable version (21.07 appears to be latest as of time of writing this issue).

## References

[ZenDesk Ticket](https://chocolatey.zendesk.com/agent/tickets/13392)

### PR DESCRIPTION
**Pull request by gep13**
## Description Of Changes

Upgrade to latest 7zip binaries.

## Motivation and Context

There are no CVE's associated with the previous release, however, since
the last version was shipped in 2018, it was decided to upgrade to a
newer version.

## Testing

1. Built new nupkg with changes in this PR
1. Installed onto machine for testing
1. Installed the sqlite package (which includes usage of the Get-ChocolateyUnZip cmdlet)
1. Verified that it installed as expected, with no errors

## Change Types Made

* [ ] Bug fix (non-breaking change)
* [x] Feature / Enhancement (non-breaking change)
* [ ] Breaking change (fix or feature that could cause existing functionality to change)

## Related Issue

Fixes #2650

## Change Checklist

* [ ] Requires a change to the documentation
* [ ] Documentation has been updated
* [ ] Tests to cover my changes, have been added
* [x] All new and existing tests passed.

### CODE REVIEW

**Comment by gep13** [comment]
If/when this is merged, a follow up PR to CCR will be required to bump the 7za.exe that is stored there to be the same version, so that everything is consistent.

**Review by corbob — APPROVED** [review]
I've taken this for a spin with the Intune integration, it's all working as expected. I'm just running a test kitchen run against it, will know before Monday if there's any issues with those tests.

**Comment by corbob** [comment]
<details>

<summary> Well that didn't go quite as planned...


</summary>

<p>
Those 15 failed are expected due to the build identifying as `0.12.1-alpha` and those tests only skipping if the version is 1.0.0 or greater.
</p>

</details>

**Comment by gep13** [comment]
@corbob thanks for taking this for a spin!

**Pull request merged**
