### PR TITLE
Use HTTPS in README.md

### PR DESCRIPTION
**Pull request by Dennis14e**

### CODE REVIEW

**Comment by ferventcoder** [comment]
Thanks. This is considered a trivial contribution to the readme docs and as such does not require a CLA signature.

**Comment by gep13** [comment]
@ferventcoder AppVeyor is currently experiencing an outage:

https://appveyor.statuspage.io/

So unlikely that you will get a response back on the outstanding build just now.

**Comment by ferventcoder** [comment]
Got a bit too quick there, forgot about asking for it to be converted to `(maint)` or `(doc)`. O well, no worries.

**Comment by gep13** [comment]
@ferventcoder looks like AppVeyor is ok again: https://appveyor.statuspage.io/

**Pull request merged**
