### PR TITLE
(GH-427) Add paging to ListCommand

### PR DESCRIPTION
**Pull request by RichiCoder1**
See #427.

Adds `--page=#` and `--page-size=#` to `ListCommand`. Page size defaults to 25.

### CODE REVIEW

**Comment by ferventcoder** [comment]
Oh wow, I can't wait to play with this just in regular choco.

**Comment by RichiCoder1** [comment]
About the only flaw with this is it currently only works for Nuget. Nuget it is the worst offender, but I'll leave it up to you if you want me to fix the other source providers in this PR, or another.

**Comment by ferventcoder** [comment]
Let's go there appveyor.

**Comment by ferventcoder** [comment]
> only works for Nuget

Like only NuGet sources?

**Comment by RichiCoder1** [comment]
Yup. Nuget is the only source runner that respects the option currently. Cygwin, Python, RubyGems, WebPI, and WindowsFeature currently simply just ignore it.

**Comment by RichiCoder1** [comment]
Though it looks like Cygwin doesn't implement list. Just the others.

**Pull request merged**
