### PR TITLE
Support for custom headers downloading files

### PR DESCRIPTION
**Pull request by patrickmaurer**
Changes made by @ewilde taken from chocolatey/chocolatey/pull/171

### CODE REVIEW

**Comment by ferventcoder** [comment]
Hi @patrickmaurer - can you please review our CONTRIBUTING.md document and adjust this PR for the changes you will need to make to the commit message (including filing an issue in this code base so you can reference it in your commit), signing the CLA and other such items? Thanks!

**Comment by ferventcoder** [comment]
The code itself looks fine.

**Comment by ferventcoder** [comment]
@patrickmaurer have you had an opportunity to review my feedback and respond?

**Comment by patrickmaurer** [comment]
Well the CLA thing frightened my a bit because of
1. the code isn't mine but from @ewilde (chocolatey/chocolatey#171)
2. the CLA legalese itself didn't make me feel very comfortable, I also don't like to disclose all my personal details

**Comment by ferventcoder** [comment]
That's fair - I don't share CLA details with anyone. Unless litigation comes up, then I would share those details, but only selectively. That's an extreme, I don't expect anything of the sort.

Perhaps @ewilde could provide the PR instead? :/

**Comment by ewilde** [comment]
@ferventcoder yep happy to do that. Will review the contributing.md and create a new PR

**Comment by ferventcoder** [comment]
Closed via #329

**Pull request closed without merging**
