### PR TITLE
(GH-184) Show a prompt character

### PR DESCRIPTION
**Pull request by christianrondeau**
Solves #184, depends on PR #204.

Simply adds a `>` character before prompting in multiple choices questions. (Probably my simplest PR ever :stuck_out_tongue:

### CODE REVIEW

**Comment by christianrondeau** [comment]
Rebased and merged with #181 (since they are almost the same set of changes)

**Comment by christianrondeau** [comment]
Ready to merge

**Comment by ferventcoder** [comment]
Thanks, already have these in mind for 0.9.10

**Comment by ferventcoder** [comment]
Superseded by #204

**Pull request closed without merging**
