### PR TITLE
(GH-1899) Remove unused variables

### LINKED ISSUE #1899: (doc) Install-ChocolateyPackage - example 3 seems to be incorrect or incomplete, not calling the .msi variables
Hi,
On this page:
https://chocolatey.org/docs/helpers-install-chocolatey-package

Look the example 3:

$url        = 'https://somewhere.com/file.msi'
$url64      = 'https://somewhere.com/file-x64.msi'

It's never calling these variables.

Maybe:
A: a step is missing in the example
B: there's a copy paste error in the example

Can you please have a look and fix it?

Cheers,

### PR DESCRIPTION
**Pull request by FLeXyo**
Fixes #1899 

This is my first contribution, be gentle :)

### CODE REVIEW

**Comment by ferventcoder** [comment]
@FLeXyo thanks! This is valid.

**Review by gep13 — APPROVED** [review]
LGTM!

**Review by gep13 — APPROVED** [review]
LGTM!

**Comment by gep13** [comment]
@FLeXyo thank you for taking the time to submit this PR, really appreciate it!

**Pull request merged**
