### PR TITLE
(#3364) Fix broken tab completion (expansion) in PowerShell v7.4+ 

### LINKED ISSUE #3364: Tab completion does not work since PowerShell 7.4
### Checklist

- [X] I have verified this is the correct repository for opening this issue.
- [X] I have verified no other issues exist related to my problem.
- [X] I have verified this is not an issue for a specific package.
- [X] I have verified this issue is not security related.
- [X] I confirm I am using **official**, and **not** unofficial, or modified, Chocolatey products.

### What You Are Seeing?

Hitting tab after typing `choco ` only shows filenames

### What is Expected?

Choco commands like `install`, `upgrade`, etc. should be shown

### How Did You Get This To Happen?

1. Make sure PowerShell profile contains the following snippet
```
$ChocolateyProfile = "$env:ChocolateyInstall\helpers\chocolateyProfile.psm1"
if (Test-Path($ChocolateyProfile)) {
  Import-Module "$ChocolateyProfile"
}
```
2. Upgrade PowerShell to 7.4.0
3. Type `choco ` and hit tab

### System Details

* Operating System: 10.0.19045.0
* Windows PowerShell version: 
```
Name                           Value
----                           -----
PSVersion                      7.4.0
PSEdition                      Core
GitCommitId                    7.4.0
OS                             Microsoft Windows 10.0.19045
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```
* Chocolatey CLI Version: 2.2.2
* Chocolatey Licensed Extension version: N/A - `0 packages installed.`
* Chocolatey License type: Open Source
* Terminal/Emulator: PowerShell Core 7.4.0 on Microsoft Terminal 1.18.3181.0

### Installed Packages

```bash
au 2022.10.24
chocolatey 2.2.2
chocolatey-compatibility.extension 1.0.0
chocolatey-core.extension 1.4.0
chocolatey-windowsupdate.extension 1.0.5
dellcommandupdate 5.1.0
delta 0.16.5
DotNet4.6.1 4.6.1055.20170308
Firefox 120.0.0
git.install 2.43.0
gnupg 2.4.3
KB2919355 1.0.20160915
KB2919442 1.0.20160915
KB2999226 1.0.20181019
KB3033929 1.0.5
KB3035131 1.0.3
KB3118401 1.0.5
kdeconnect-kde 23.4.0
keepassxc 2.7.6
libreoffice-still 7.5.8
microsoft-windows-terminal 1.18.3181
miktex.install 23.10.12
neovim 0.9.4
nodejs-lts 20.10.0
notepadplusplus.install 8.6.0
PIME 1.3.0
powershell-core 7.4.0
python39 3.9.13.20230703
ripgrep 13.0.0.20220913
syncthingtray 1.4.9
synergy 1.14.6.19
texstudio.install 4.6.3
vcredist140 14.38.33130
vcredist2015 14.0.24215.20170201
```

### Output Log

```bash
(N/A - not sure how to get logs for tab completion)
```

### Additional Context

The cause is that Chocolatey only defines `TabExpansion` function to enable completions, while that function is no longer used by PowerShell 7.4 [1]. A solution might be adding `TabExpansion2` function (supported since PowerShell 3) besides the existing `TabExpansion` function, so that all users with PowerShell 2 ~ 7.4 can have Chocolatey tab completions.

As a side note, if `TabExpansion2` is added, https://github.com/chocolatey/choco/issues/2255 will likely be solved as well.

[1] https://github.com/PowerShell/PowerShell/pull/18337

### PR DESCRIPTION
**Pull request by mklement0**
## Description Of Changes

Switches to using `Register-ArgumentCompleter` for tab-completion (expansion) when running in PowerShell v7.4+

## Motivation and Context

As discussed in #3364:

* Chocolatey's tab completion broke in v7.4.0, due to an intentional breaking change in PowerShell (removal of legacy code, as a side effect of which PowerShell no longer calls custom `TabExpansion` functions, if defined).

* The recommended approach (since v5.0) is to use `Register-ArgumentCompleter`

## Testing

* Interactively (tab completion).

* Programmatically, by calling `TabExpansion2`; e.g:

```
(TabExpansion2 ($c = 'choco c') -cursorColumn $c.Length).CompletionMatches.CompletionText | 
  Should -Be cache, config
(TabExpansion2 ($c = 'choco l later') -cursorColumn 7).CompletionMatches.CompletionText |
  Should -Be list
```

### Operating Systems Testing

Windows 11 22H2

## Change Types Made

* [x] Bug fix (non-breaking change).
* [ ] Feature / Enhancement (non-breaking change).
* [ ] Breaking change (fix or feature that could cause existing functionality to change).
* [ ] Documentation changes.
* [x] PowerShell code changes.

## Change Checklist

* [ ] Requires a change to the documentation.
* [ ] Documentation has been updated.
* [ ] Tests to cover my changes, have been added.
* [ ] All new and existing tests passed?
* [ ] PowerShell code changes: PowerShell v2 compatibility checked?

I don't have access to PowerShell v2, but I _think_ the changes are compatible.

## Related Issue

Fixes #3364

### CODE REVIEW

**Comment by yan12125** [comment]
How do you think about using `Register-ArgumentCompleter` on PowerShell >= 5.0 instead of PowerShell >= 7.4? That will help https://github.com/chocolatey/choco/issues/2255 for users on a little bit older PowerShell.

**Comment by mklement0** [comment]
I tried to be conservative, but, yes, it should be possible to use `Register-ArgumentCompleter` in v5+

However, support for `choco.exe` is really a separate issue (I just happened to add it to the v7.4+ code - though I just reverted it, because it was incomplete and introduces an asymmetry).

The only thing needed to enable it for the v7.3- code is the following:

Change the `$aliase=...` line in:

```powershell
function Get-AliasPattern($exe) {
    $aliases = @($exe) + @(Get-Alias | Where-Object { $_.Definition -eq $exe } | Select-Object -Exp Name)

    "($($aliases -join '|'))"
}
```

to:

```powershell
    $aliases = @($exe, "$exe\.exe") + @(Get-Alias | Where-Object { $exe, "$exe.exe" -contains $_.Definition } | Select-Object -Exp Name)
```

If the maintainers are fine with this, I'm happy to update the PR to add `choco.exe` support in all versions.

**Comment by yan12125** [comment]
Oops, I misunderstood the issue about `choco.exe`. Many thanks for the kind explanation!

**Review by silverqx — APPROVED** [review]
I tried this PR and it works well, everything looks good short, long parameters, completion of commands and also completion of package names.

This PR lgtm. Why it's still not merged?

**Comment by yan12125** [comment]
There are merge conflicts in `src/chocolatey.resources/helpers/chocolateyProfile.psm1` after commit https://github.com/chocolatey/choco/commit/186ffc840f91944f5939080cbc78140f71ec4506. Mind to do a rebase?

> This PR lgtm. Why it's still not merged?

It seems pull requests towards Chocolatey repositories are often kept open for a long time. [My other pull request](https://github.com/chocolatey-community/chocolatey-packages/pull/2250) has been there for almost one year.

**Comment by mklement0** [comment]
@yan12125, it looks like the only reason for the conflict is that a signature was added, which I cannot recreate myself.

**Comment by yan12125** [comment]
> which I cannot recreate myself.

Do you mean that you cannot create new signatures? Apparently new signatures will be created by maintainers after scripts are updated. For example, after scripts are changed in dc409a3de0c03a29d95fec73a555a5d4fedc4ac3, signatures are updated in d8821c8c1b3c00a008aaaf44f879b8503881d4c6. As a result, I'd assume it's enough to resolve conflicts in scripts without touching signatures.

**Comment by mklement0** [comment]
@yan12125, yes, I meant the signature. I took your advice and resolved the conflict while keeping the - by definition now invalid - signature.

**Comment by yan12125** [comment]
Thank you! Hopefully some dev will have a look at this soon.

**Comment by gep13** [comment]
@mklement0 thank you for taking the time for creating this PR, and for getting it updated.

Before we will be able to look at this, and get it merged in, the PR will need to conform to the guidelines that are stipulated in the CONTRIBUTING document for this repository.  Can I get you to look through that document, specifically the "prepare commits` [section](https://github.com/chocolatey/choco/blob/develop/CONTRIBUTING.md#prepare-commits).

**Comment by mklement0** [comment]
@gep13, I fully understand that, as a high-profile project, you need to enforce standards on community PRs.

However, personally, as an infrequent Chocolatey user, I'm not willing to invest the time to learn how to conform to those standards.

I hope someone else is, though, and they're free to base their future PR on the code in this one.

**Comment by yan12125** [comment]
> I hope someone else is, though, and they're free to base their future PR on the code in this one.

Thanks, I created a new pull request from your codes https://github.com/chocolatey/choco/pull/3459

**Comment by mklement0** [comment]
Thank you, @yan12125.

**Pull request closed without merging**
