### PR TITLE
Set Docker.windows to ltsc2019

### PR DESCRIPTION
**Pull request by gliptak**
Signed-off-by: Gábor Lipták gliptak@gmail.com

## Description Of Changes

To match setup in GHA

## Change Types Made

* [ ] Bug fix (non-breaking change)
* [ ] Feature / Enhancement (non-breaking change)
* [ ] Breaking change (fix or feature that could cause existing functionality to change)
* [ ] PowerShell code changes.

## Related Issue

Fixes #

## Change Checklist

* [ ] Requires a change to the documentation
* [ ] Documentation has been updated
* [ ] Tests to cover my changes, have been added
* [ ] All new and existing tests passed.
* [ ] PowerShell v2 compatibility checked.

### CODE REVIEW

**Comment by gep13** [comment]
@gliptak thank you for taking the time to submit this PR!

Can you expand on this:

> To match setup in GHA

Why exactly do you feel this is necessary?  The decision was taken to use the 2016 base image since it can be used in the most places.  At some point, we would look to expand the number of base images to include other operating systems, but this is not something that has been prioritised yet.

**Comment by gliptak** [comment]
@gep13thank you for the details. this PR matches Docker with GHA (already on 2019)

https://github.com/chocolatey/choco/blob/develop/.github/workflows/build.yml#L41

**Comment by TheCakeIsNaOH** [comment]
@gliptak the Github Actions build is using Server 2019 because it is the oldest official Windows server version available. It still builds Chocolatey for .Net 4.0 (currently), which would run on Windows versions back to Server 2012.

The reason the Windows dockerfile is based on Server 2016, is so Windows hosts back to server 2016 can run the image. Uplifting the base image in the dockerfile would prevent Server 2016 hosts from running the image.

**Comment by gliptak** [comment]
thank you for the details @TheCakeIsNaOH closing

**Pull request closed without merging**
