### PR TITLE
Update ShimGen license in CREDITS.md

### PR DESCRIPTION
**Pull request by vexx32**
## Description Of Changes

- Update ShimGen license in CREDITS.md
- Fix TOCs in CREDITS.md, ensure the shortlinks work, etc.

## Motivation and Context

@corbob noticed that the shimgen license copy in the CREDITS document was out of date. We should keep these as up to date as possible.

## Testing

- License in CREDITS.md should match the current license of [ShimGen](/chocolatey/shimgen).

## Change Types Made

* [x] Doc fix
* [ ] Bug fix (non-breaking change)
* [ ] Feature / Enhancement (non-breaking change)
* [ ] Breaking change (fix or feature that could cause existing functionality to change)
* [ ] PowerShell code changes.

## Related Issue

N/A

## Change Checklist

* [ ] Requires a change to the documentation
* [x] Documentation has been updated
* [ ] Tests to cover my changes, have been added
* [ ] All new and existing tests passed.
* [ ] PowerShell v2 compatibility checked.

### CODE REVIEW

**Comment by corbob** [comment]
Was it intentional for commit `281acee8791596f02cdb8c7e872d20bfc8950099` to change the line endings? (I haven't looked at a diff showing the line endings, but GitHub interface when whitespace is not hidden shows the entire file being changes...)

**Review by corbob — APPROVED** [review]
LGTM!

**Comment by vexx32** [comment]
Beats me as to how that particular commit was borked tbh. I checked the line endings and the BOM, and they both matched the original file as far as I could tell.

Weirdness. 🤷‍♀️ 

Fixed at least, somehow.

**Comment by corbob** [comment]
Thanks for getting this updated @vexx32

**Pull request merged**
